[build]
  command = "cd packages/sveltekit && pnpm run build"
  publish = "packages/sveltekit/build/"
  functions = "packages/sveltekit/.netlify/functions-internal/"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[plugins]]
  package = "netlify-plugin-contextual-env"
[functions]
  node_bundler = "esbuild"